#pragma once

#include <cstdint>
#include <string>

namespace hogak::engine {

struct EngineMetrics {
    std::string status = "idle";
    std::string sync_pair_mode = "-";
    int64_t frame_index = 0;
    double left_fps = 0.0;
    double right_fps = 0.0;
    double left_avg_frame_interval_ms = 0.0;
    double right_avg_frame_interval_ms = 0.0;
    double left_last_frame_interval_ms = 0.0;
    double right_last_frame_interval_ms = 0.0;
    double left_max_frame_interval_ms = 0.0;
    double right_max_frame_interval_ms = 0.0;
    int64_t left_late_frame_intervals = 0;
    int64_t right_late_frame_intervals = 0;
    double left_buffer_span_ms = 0.0;
    double right_buffer_span_ms = 0.0;
    double left_avg_read_ms = 0.0;
    double right_avg_read_ms = 0.0;
    double left_max_read_ms = 0.0;
    double right_max_read_ms = 0.0;
    int64_t left_buffer_seq_span = 0;
    int64_t right_buffer_seq_span = 0;
    double left_age_ms = 0.0;
    double right_age_ms = 0.0;
    double left_source_age_ms = 0.0;
    double right_source_age_ms = 0.0;
    double selected_left_lag_ms = 0.0;
    double selected_right_lag_ms = 0.0;
    int64_t selected_left_lag_frames = 0;
    int64_t selected_right_lag_frames = 0;
    double left_motion_mean = 0.0;
    double right_motion_mean = 0.0;
    double stitched_motion_mean = 0.0;
    double stitch_fps = 0.0;
    double stitch_actual_fps = 0.0;
    double worker_fps = 0.0;
    double output_written_fps = 0.0;
    double production_output_written_fps = 0.0;
    double pair_skew_ms_mean = 0.0;
    double pair_source_skew_ms_mean = 0.0;
    bool source_time_valid_left = false;
    bool source_time_valid_right = false;
    std::string source_time_mode = "fallback-arrival";
    double sync_effective_offset_ms = 0.0;
    std::string sync_offset_source = "arrival-fallback";
    double sync_offset_confidence = 0.0;
    int64_t sync_recalibration_count = 0;
    int32_t matches = 0;
    int32_t inliers = 0;
    int64_t stitched_count = 0;
    int64_t reused_count = 0;
    int64_t wait_both_streams_count = 0;
    int64_t wait_sync_pair_count = 0;
    int64_t wait_next_frame_count = 0;
    int64_t wait_paired_fresh_count = 0;
    int64_t wait_paired_fresh_left_count = 0;
    int64_t wait_paired_fresh_right_count = 0;
    int64_t wait_paired_fresh_both_count = 0;
    double wait_paired_fresh_left_age_ms_avg = 0.0;
    double wait_paired_fresh_right_age_ms_avg = 0.0;
    int64_t realtime_fallback_pair_count = 0;
    bool gpu_enabled = false;
    std::string gpu_reason = "-";
    bool gpu_feature_enabled = false;
    std::string gpu_feature_reason = "-";
    int64_t gpu_warp_count = 0;
    int64_t cpu_warp_count = 0;
    int64_t gpu_match_count = 0;
    int64_t cpu_match_count = 0;
    int64_t gpu_blend_count = 0;
    int64_t cpu_blend_count = 0;
    int64_t gpu_errors = 0;
    int64_t gpu_feature_errors = 0;
    std::string blend_mode = "-";
    double overlap_diff_mean = 0.0;
    double stitched_mean_luma = 0.0;
    double left_mean_luma = 0.0;
    double right_mean_luma = 0.0;
    double warped_mean_luma = 0.0;
    int64_t only_left_pixels = 0;
    int64_t only_right_pixels = 0;
    int64_t overlap_pixels = 0;
    bool manual_mode = false;
    int32_t manual_left = 0;
    int32_t manual_right = 0;
    int32_t manual_target = 0;
    int64_t left_frames_total = 0;
    int64_t right_frames_total = 0;
    int64_t left_buffered_frames = 0;
    int64_t right_buffered_frames = 0;
    int64_t left_stale_drops = 0;
    int64_t right_stale_drops = 0;
    int64_t left_launch_failures = 0;
    int64_t right_launch_failures = 0;
    int64_t left_read_failures = 0;
    int64_t right_read_failures = 0;
    int64_t left_reader_restarts = 0;
    int64_t right_reader_restarts = 0;
    bool left_content_frozen = false;
    bool right_content_frozen = false;
    double left_frozen_duration_sec = 0.0;
    double right_frozen_duration_sec = 0.0;
    int64_t left_freeze_restarts = 0;
    int64_t right_freeze_restarts = 0;
    bool output_active = false;
    int64_t output_frames_written = 0;
    int64_t output_frames_dropped = 0;
    std::string output_target;
    std::string output_command_line;
    std::string output_effective_codec;
    std::string output_last_error;
    bool production_output_active = false;
    int64_t production_output_frames_written = 0;
    int64_t production_output_frames_dropped = 0;
    std::string production_output_target;
    std::string production_output_command_line;
    std::string production_output_effective_codec;
    std::string production_output_last_error;
    bool calibrated = false;
    int32_t output_width = 0;
    int32_t output_height = 0;
    int32_t production_output_width = 0;
    int32_t production_output_height = 0;
    std::string left_last_error;
    std::string right_last_error;
};

}  // namespace hogak::engine
